In [1]:
import torch
import numpy as np

# Creating Matrices

In [2]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [3]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [4]:
# Convert to PyTorch Tensor
torch.Tensor(arr)


 1  2
 3  4
[torch.FloatTensor of size 2x2]

In [5]:
#Create 2x2 numpy array of 1's
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [6]:
#Create 2x2 torch tensor of 1's
torch.ones((2, 2))


 1  1
 1  1
[torch.FloatTensor of size 2x2]

In [7]:
#Create 2x2 numpy array of random numbers
np.random.rand(2, 2)

array([[ 0.00765202,  0.03242343],
       [ 0.79268459,  0.00189121]])

In [8]:
#Create 2x2 PyTorch tensor of random numbers
torch.rand(2, 2)


 0.9133  0.9012
 0.3302  0.7886
[torch.FloatTensor of size 2x2]

# Seeds for Reproducibility

In [9]:
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [10]:
#Repeat random array generation to check
# Seed
np.random.seed(0)
np.random.rand(2, 2)

array([[ 0.5488135 ,  0.71518937],
       [ 0.60276338,  0.54488318]])

In [11]:
#Create a numpy array without seed
# No seed
np.random.rand(2, 2)

array([[ 0.4236548 ,  0.64589411],
       [ 0.43758721,  0.891773  ]])

In [12]:
#Repeat numpy array generation without seed
np.random.rand(2, 2)

array([[ 0.96366276,  0.38344152],
       [ 0.79172504,  0.52889492]])

In [13]:
#Create a PyTorch tensor with a fixed seed
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)


 0.4963  0.7682
 0.0885  0.1320
[torch.FloatTensor of size 2x2]

In [ ]:
#Repeat creating a PyTorch fixed seed tensor
# Torch Seed
torch.manual_seed(0)
torch.rand(2, 2)

In [ ]:
#Creating a PyTorch tensor without seed
# Torch No Seed
torch.rand(2, 2)

In [ ]:
#Repeat creating a PyTorch tensor without seed
# Torch No Seed
torch.rand(2, 2)

# Seed for GPU is different for now...

In [15]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

# NumPy and Torch Bridge

In [16]:
#NumPy to Torch
np_array = np.ones((2, 2))
print(np_array)

[[ 1.  1.]
 [ 1.  1.]]


In [17]:
#Get the type of class for the numpy array
print(type(np_array))

<class 'numpy.ndarray'>


In [18]:
#Convert numpy array to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)
print(torch_tensor)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]



In [19]:
#Get type of class for PyTorch tensor
print(type(torch_tensor))

<class 'torch.DoubleTensor'>


In [20]:
#Create PyTorch tensor from a different numpy datatype
# Data types matter: intentional error
np_array_new = np.ones((2, 2), dtype=np.int8)
torch.from_numpy(np_array_new)

RuntimeError: can't convert a given np.ndarray to a tensor - it has an invalid type. The only supported types are: double, float, int64, int32, and uint8.

In [ ]:
#What conversion support does Numpy to PyTorch tensor bridge gives?
#double
#float
#int64, int32, uint8

In [21]:
#Create PyTorch long tensor

In [22]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.LongTensor of size 2x2]

In [23]:
#Create PyTorch int tensor

In [24]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.int32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.IntTensor of size 2x2]

In [25]:
#Create PyTorch byte tensor
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.uint8)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.ByteTensor of size 2x2]

In [26]:
#Create PyTorch Double Tensor

In [27]:
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float64)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [28]:
#Alternatively you can do this too via np.double
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.double)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.DoubleTensor of size 2x2]

In [29]:
#Create PyTorch Float Tensor
# Data types matter
np_array_new = np.ones((2, 2), dtype=np.float32)
torch.from_numpy(np_array_new)


 1  1
 1  1
[torch.FloatTensor of size 2x2]

# Torch to NumPy

In [32]:
#Create PyTorch tensor of 1's

In [33]:
torch_tensor = torch.ones(2, 2)
type(torch_tensor)

torch.FloatTensor

In [34]:
#Convert tensor to numpy

In [35]:
torch_to_numpy = torch_tensor.numpy()
type(torch_to_numpy)

numpy.ndarray

# Tensors on CPU vs GPU¶

In [36]:
#This by default creates a tensor on CPU. You do not need to do anything.
# CPU
tensor_cpu = torch.ones(2, 2)

In [37]:
# CPU to GPU
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
tensor_cpu.to(device)

AttributeError: module 'torch' has no attribute 'device'

In [38]:
#And if you want to move that tensor on the GPU back to the CPU, just do the following.
# GPU to CPU
tensor_cpu.cpu()


 1  1
 1  1
[torch.FloatTensor of size 2x2]

# Tensor Operations

In [39]:
#Creating a 2x2 tensor
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [40]:
#Getting size of tensor
print(a.size())

torch.Size([2, 2])


In [41]:
#Resize tensor to 4x1
a.view(4)


 1
 1
 1
 1
[torch.FloatTensor of size 4]

In [42]:
#Get size of resized tensor

In [43]:
a.view(4).size()

torch.Size([4])

In [44]:
#Element-wise Addition
a = torch.ones(2, 2)
print(a)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [45]:
#Creating second 2x2 tensor
b = torch.ones(2, 2)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [46]:
#Element-wise addition of 2 tensors
c = a + b
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [47]:
#Alternative element-wise addition of 2 tensors
# Element-wise addition
c = torch.add(a, b)
print(c)


 2  2
 2  2
[torch.FloatTensor of size 2x2]



In [48]:
#In-place element-wise addition
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)
print('New c tensor')
print(c)

Old c tensor

 2  2
 2  2
[torch.FloatTensor of size 2x2]

------------------------------------------------------------
New c tensor

 3  3
 3  3
[torch.FloatTensor of size 2x2]



In [49]:
#Element-wise Subtraction
print(a)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [50]:
a - b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [51]:
print(a.sub(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [52]:
## Inplace
print(a.sub_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [53]:
#Element-Wise Multiplication
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [54]:
a * b


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [55]:
# Not in-place
print(torch.mul(a, b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 1  1
 1  1
[torch.FloatTensor of size 2x2]



In [56]:
# In-place
print(a.mul_(b))
print(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [57]:
#Element-Wise Division
a = torch.ones(2, 2)
print(a)
b = torch.zeros(2, 2)
print(b)


 1  1
 1  1
[torch.FloatTensor of size 2x2]


 0  0
 0  0
[torch.FloatTensor of size 2x2]



In [58]:
#Element-wise division: method 1
b / a


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [59]:
torch.div(b, a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

In [60]:
# Inplace
b.div_(a)


 0  0
 0  0
[torch.FloatTensor of size 2x2]

# Tensor Mean

In [61]:
#Create tensor of size 10 filled from 1 to 10
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [62]:
#Get tensor mean
a.mean(dim=0)


 5.5000
[torch.FloatTensor of size 1]

In [64]:
#Get tensor mean on second dimension
a.mean(dim=1)

RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

In [65]:
#Create a 2x10 Tensor, of 1-10 digits each
a = torch.Tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
a.size()

torch.Size([2, 10])

In [66]:
#Get tensor mean on second dimension
a.mean(dim=1)


 5.5000
 5.5000
[torch.FloatTensor of size 2]

In [67]:
#Tensor Standard Deviation¶
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)


 3.0277
[torch.FloatTensor of size 1]