In [2]:
#Creating Tensors with Gradients

In [2]:
import torch

In [3]:
#Method 1: Create tensor with gradients
#a = torch.autograd.Variable(torch.randn((3,5)), requires_grad=True)
a = torch.ones((2, 2), requires_grad=True)
a


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [4]:
a.requires_grad

True

In [5]:
#Method 2: Create tensor with gradients
# Normal way of creating gradients
a = torch.ones((2, 2))

# Requires gradient
a.requires_grad_()

# Check if requires gradient
a.requires_grad

True

In [7]:
#A tensor without gradients just for comparison
no_gradient = torch.ones(2, 2)
no_gradient.requires_grad

False

# Tensor with gradients addition operation

In [8]:
# Behaves similarly to tensors
b = torch.ones((2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<ThAddBackward>)


In [9]:
#Tensor with gradients multiplication operation
print(a * b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<ThMulBackward>)


# Manually and Automatically Calculating Gradients¶

In [10]:
x = torch.ones(2, requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [11]:
#Simple linear equation with x tensor created
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward>)

In [13]:
#Backward
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward>)

In [14]:
o.backward()

In [15]:
x.grad

tensor([10., 10.])

In [16]:
print(x.requires_grad)
print(y.requires_grad)
print(o.requires_grad)

True
True
True
