In [3]:
## Advanced Neural network in numpy 可自行設定層數

import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Sigmoid Function for backpropagation
def derivatives_sigmoid (x):
    return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)#做內積
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

  #Backpropagation
  E = y-output #Los差異
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T) #轉置後才能乘back_hidden_layer
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr #乘以學習率之後，再每次迴圈判斷Error
  bout += np.sum(d_output, axis=0,keepdims=True) *lr #乘以學習率之後，再每次迴圈判斷Error
  wh += X.T.dot(d_hiddenlayer) *lr 
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr #keepdims保持矩陣二維特性


print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[1]
 [1]
 [0]] 

predicted :
 [[0.9789878 ]
 [0.96934528]
 [0.0451999 ]]


In [6]:
## neural network in pytorch
import torch
import numpy as np

#Input array
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
  return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)

#Variable initialization
epoch=1000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 10 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor) #1=size
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)#1=size

#wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
#bh=np.random.uniform(size=(1,hiddenlayer_neurons))
#wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
#bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):

  #Forward Propogation
  hidden_layer_input1 = torch.mm(X, wh) # torch.mm = np.dot
  hidden_layer_input = hidden_layer_input1 + bh
  hidden_layer_activations = sigmoid(hidden_layer_input)
 
  output_layer_input1 = torch.mm(hidden_layer_activations, wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input1)

  #Backpropagation
  E = y-output
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = torch.mm(d_output, wout.t())
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
  bout += d_output.sum() *lr
  wh += torch.mm(X.t(), d_hiddenlayer) *lr
  bh += d_output.sum() *lr

  ##Loss 先將數值轉numpy
  #numpy_E = E.numpy() 
  #Loss_E = np.sum((numpy_E)**2)/len(numpy_E)
  #print("E",Loss_E)
  #if i % 10 == 0: #取餘數，讓他變成10次顯示一次
  #  print("Epoch: {} loss {}".format(i, Loss_E))
 
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[ 1.],
        [ 1.],
        [ 0.]]) 

predicted :
 tensor([[ 0.9655],
        [ 0.9483],
        [ 0.0640]])


In [ ]:
#試試迭代次數變少
#試試層數減少
#試試層數為1、epoch為10
#加上MSE
#整理迭代的內容，如何讓每十次顯示一個迭代